#Do not change the below config version
version: 2.2
#Holds the last tagged player
taggedPlayer: "noPlayer"
#Set below to true if you want to broadcast when a player opts in or out of tag
broadcastOpt: true
#Tag cooldown in seconds to re-tag the same player
cooldown: 5
#Set below to true if you want to use scoreboards, false if not
scoreboards: true
#Set below to false if you do not want the auto re-tag on leave to trigger (When tagged player quits)
autoTagOnLeave: true